# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "pycram/semantic_world:jazzy"
    steps:
    - uses: actions/checkout@v4
      with:
        path: "ros/src/semantic_world"
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        submodules: 'false'
    - name: Update semantic_world source files
      run: |
        rm -rf /opt/ros/overlay_ws/src/semantic_world/* 
        cd /opt/ros/overlay_ws/src/semantic_world
        rm -rf .git .github .gitignore .gitmodules .readthedocs.yaml
        cp -r /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ros/src/semantic_world /opt/ros/overlay_ws/src

    - name: Install dependencies
      run: |
        sudo apt-get update
        cd /opt/ros/overlay_ws/src/semantic_world
        source ../semantic_world-venv/bin/activate    
        pip install -U pip && pip install -r requirements.txt && pip install . && pip install -r doc/requirements.txt
        echo "PATH=$PWD/ultiverse-Parser/ext/blender:$PWD/ultiverse-Parser/USD/linux/lib/python:$PWD/ultiverse-Parser/USD/linux/plugin/usd:$PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/ultiverse-Parser/USD/linux/lib/python:$PWD/src" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd /opt/ros/overlay_ws/src/semantic_world
        source ../semantic_world-venv/bin/activate 
        pytest -v test/
